apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Airflow PostgreSQL
    type: postgres
    uid: airflow-postgres
    access: proxy
    url: postgres:5432
    database: airflow
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      sslmode: disable
      postgresVersion: 1300
    editable: false

  # ClickHouse из docker-compose_cluster.yml (общая сеть click_network)
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    access: proxy
    url: http://clickhouse01:8123
    jsonData:
      defaultDatabase: default
      username: admin
      tlsSkipVerify: true
    secureJsonData:
      password: admin
    editable: false
